export const CHECK_BOOKING_REQUEST = 'CHECK_BOOKING_REQUEST'
export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS'
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET'
export const CHECK_BOOKING_FAIL = 'CHECK_BOOKING_FAIL'

export const BOOKED_DATES_SUCCESS = 'BOOKED_DATES_SUCCESS'
export const BOOKED_DATES_FAIL = 'BOOKED_DATES_FAIL'

export const MY_BOOKINGS_SUCCESS = 'MY_BOOKINGS_SUCCESS'
export const MY_BOOKINGS_FAIL = 'MY_BOOKINGS_FAIL'

export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

export const ADMIN_BOOKINGS_REQUEST = 'ADMIN_BOOKINGS_REQUEST'
export const ADMIN_BOOKINGS_SUCCESS = 'ADMIN_BOOKINGS_SUCCESS'
export const ADMIN_BOOKINGS_FAIL = 'ADMIN_BOOKINGS_FAIL'

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST'
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const DELETE_BOOKING_RESET = 'DELETE_BOOKING_RESET'
export const DELETE_BOOKING_FAIL = 'DELETE_BOOKING_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'